php:
  image: php:fpm-alpine
  expose:
    - "9000:9000"
  links:
    - mysql:mysql
  volumes_from:
    - data

nginx:
  image: nginx:alpine
  ports:
    - "80:80"
  links:
    - php
  volumes_from:
    - data

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: 

data:
  build: .
  env_file: .env
  command: /bin/true
